# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
            - name: Run test on Autify for Mobile
  # You may pin to the exact commit or the version.
  # uses: autifyhq/actions-mobile-test-run@947f59239607effb503c765d7ee2d24ccf785fd9
  uses: autifyhq/actions-mobile-test-run@v2.5.0
  with:
    # Access token of Autify for Mobile.
    access-token: 
    # URL of a test plan e.g. https://moible-app.autify.com/projects/<ID>/test_plans/<ID>
    autify-test-url: 
    # ID of the already uploaded build. (Note: Either build-id or build-path is required but not both)
    build-id: # optional
    # File path to the iOS app (*.app) or Android app (*.apk). (Note: Either build-id or build-path is required but not both)
    build-path: # optional
    # When true, the action waits until the test finishes.
    wait: # optional, default is false
    # Timeout seconds when waiting.
    timeout: # optional
    # Maximum retry count while waiting. The command can take up to `timeout * (max-retry-count + 1)`. Only effective with `wait`
    max-retry-count: # optional
    # A path to `autify` which will be used to invoke Autify CLI internally. Default is searching from PATH.
    autify-path: # optional, default is autify
    # Autify CLI installer URL
    autify-cli-installer-url: # optional, default is https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash
          
